---
title: "Lizard Markdown"
author: "Stella Raymond"
date: "2026-05-14"
output: html_document
---

```{r setup}
#The following code was not written by the group. Credit goes to Scott
required_packages <-function(...) { 
  libs<-unlist(list(...)) 
  req<-suppressMessages(suppressWarnings(unlist(lapply(libs,require,character.only=TRUE)))) 
  need<-libs[req==FALSE] 
  if(length(need)>0){ 
    install.packages(need, repos = "http://cran.us.r-project.org") 
    lapply(need, library, character.only=TRUE) 
  }
  else{message("No packages required installation.")} 
}

required_packages("tidyverse", "emmeans", "readxl", "lmerTest", "auk", "terrainr", "ggrepel", "sf", "rebird")

sites <- data.frame(
  Campus = c("SDSU", "CSUSM", "CSUSB", "CSULB", "Cal Poly SLO", "UCLA", "Whitter","Scripps", "Harvey Mudd", "CLU", "Pepperdine"),
  Latitude  = c(32.77466, 33.12919, 34.18227, 33.78210, 35.30927, 34.07142, 33.97764, 34.10376, 34.10604, 34.22781, 34.04022),
  Longitude = c(-117.07259, -117.15697, -117.31864, -118.11464, -120.66155, -118.44289, -118.02909, -117.71214, -117.70854, -118.87794, -118.70718)
)
```

```{r temp-conversion}
f_to_c <- function(Far) {
  Cel <- ((Far-32)* (5/9))
  return(Cel)
}
```

```{r Data}
HOBO_data_half_hour <- read_xlsx("Ambient_Data.xlsx") |> 
  select(!c(Season, Time, Month))
PRISM_data <- read.csv("PRISM.csv", skip = 10) |> 
  dplyr::rename(Elevation = Elevation..ft.,
                Temp_avg = tmean..degrees.F.,
                Temp_max = tmax..degrees.F.,
                Temp_min = tmin..degrees.F., 
                Campus = Name) |> 
  mutate(Origin = "Climate",
         Temp_avg = f_to_c(Temp_avg),
         Temp_min = f_to_c(Temp_min),
         Temp_max = f_to_c(Temp_max),
         Date = ymd(Date))
```

```{r Daily-Average}
HOBO_data <- HOBO_data_half_hour |> 
  group_by(MonthDayYear, Site, Campus) |> 
  summarize(Temp_avg = mean(Temperature),
            Temp_min = min(Temperature), 
            Temp_max = max(Temperature),
            .groups = "drop_last") |> 
  dplyr::rename(Date = MonthDayYear) |> 
  ungroup() |> 
  as.data.frame() |> 
  mutate(Date = ymd(Date),
         Origin = "Microhabitat")

HOBO_data <- HOBO_data |> 
  left_join(sites, 
            by = "Campus")

```


```{r graphs}

ggplot(HOBO_data, aes(x = Date, y = Temp_min, color = Campus))+
  facet_wrap(~Site)+
  geom_point()+
  theme_bw()

ggplot(HOBO_data, aes(x = Date, y = Temp_max, color = Campus))+
  facet_wrap(~Site)+
  geom_point()+
  theme_bw()

```


```{r join}
Temp_all <- HOBO_data |> 
  full_join(PRISM_data, 
            by = c("Date", "Campus", "Origin", "Temp_avg", "Temp_min", "Temp_max", "Latitude", "Longitude")) |> 
  mutate(Site = str_replace(Site, "Off", "Non-Urban"),
         Site = str_replace(Site, "On", "Urban"),
         Origin_sp = paste(Site, Origin, sep = " "),
         Origin_sp = str_replace(Origin_sp, "NA ", ""))
  
```


```{r}
ggplot(Temp_all, aes(x = Date, y = Temp_min, color = Origin_sp))+
  geom_point(alpha = .5)+
  geom_smooth()+
  theme_bw()

ggplot(Temp_all, aes(x = Date, y = Temp_avg, color = Origin_sp))+
  geom_point()+
  theme_bw()

ggplot(Temp_all, aes(x = Date, y = Temp_max, color = Origin_sp))+
  geom_point()+
  theme_bw()
```


```{r sages-attempt-at-mapping}
#slo_county_ebird_rich
lizard_geo <- st_as_sf(sites,coords=c(x="Longitude",y="Latitude"),crs="WGS84") #Converts a regular dataframe → sf (simple features) object

lizard_geo_buf <- lizard_geo |> st_buffer(dist = 2000)

lizard_tiles <- get_tiles(lizard_geo_buf, services = "USGSTopo", resolution = 200) #Downloads map imagery (tiles) for your spatial extent

ggplot() +
  geom_spatial_rgb(data = lizard_tiles$USGSTopo, mapping = aes(x, y, r = red, g = green, b = blue)) +
  geom_sf(data = lizard_geo, alpha = .75) +
  labs(title = "xxx", 
       caption="yyy") +
  geom_label_repel(data = sites, aes(label = Campus, x = Longitude, y = Latitude), size = 3, box.padding = .5) +
  #ylim(32.5, 35.5) +
  scale_x_continuous(n.breaks = 5) +
  theme_classic() +
  theme_bw() +
  theme(
    axis.title = element_text(size = 18),
    axis.text = element_text(size = 12),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 16),
    plot.caption = element_text(size = 13))
```


```{r anova}
lmer_avg <- lmer(Temp_avg ~ Origin_sp + (1|Campus) + (1|Origin_sp:Campus),
                 data = Temp_all)
lmer_min <- lmer(Temp_min ~ Origin_sp + (1|Campus) + (1|Origin_sp:Campus),
                 data = Temp_all)
lmer_max <- lmer(Temp_max ~ Origin_sp + (1|Campus) + (1|Origin_sp:Campus),
                 data = Temp_all)

anova(lmer_avg)
anova(lmer_min)
anova(lmer_max)

pairs(emmeans(lmer_max,
              ~ Origin_sp))
```


```{r}
#| message: False

adjusted_avg <- as.data.frame(emmeans(lmer_avg, ~ Origin_sp)) |> 
  mutate(Origin_sp=fct_relevel(Origin_sp,"Urban Microhabitat", "Non-Urban Microhabitat", "Climate"))
adjusted_min <- as.data.frame(emmeans(lmer_min, ~ Origin_sp)) |> 
  mutate(Origin_sp=fct_relevel(Origin_sp,"Urban Microhabitat", "Non-Urban Microhabitat", "Climate")) 
adjusted_max <- as.data.frame(emmeans(lmer_max, ~ Origin_sp)) |> 
  mutate(Origin_sp=fct_relevel(Origin_sp,"Urban Microhabitat", "Non-Urban Microhabitat", "Climate"))

ggplot()+
  geom_jitter(data=Temp_all, alpha=.25, show.legend = F, aes(x=Origin_sp, y=Temp_avg, color=Origin_sp)) +
  geom_line(data = adjusted_avg, 
            aes(x = Origin_sp, y = emmean, color = Origin_sp), show.legend = F) +
  geom_errorbar(data = adjusted_avg, 
                aes(x = Origin_sp, ymin = asymp.LCL, ymax = asymp.UCL, color = Origin_sp), 
                width = 0.5, linewidth = 1, show.legend = F) +
  geom_point(data = adjusted_avg, 
             aes(x = Origin_sp, y = emmean, color = Origin_sp), size = 2, show.legend = F) +
  labs(caption = "Model-adjusted estimates for temperature averages compared across data origins",
       y = "Model-Adjusted Temperature", 
       x = "Recording Origin") +
  theme_bw() +
  theme(
    panel.grid = element_blank(), 
    axis.line = element_line(color = "black"),
    axis.title = element_text(size = 18),
    axis.text = element_text(size = 12),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 16),
    plot.caption = element_text(size = 13))

ggplot()+
  geom_jitter(data=Temp_all, alpha=.25, show.legend = F, aes(x=Origin_sp, y=Temp_min, color=Origin_sp)) +
  geom_line(data = adjusted_min, 
            aes(x = Origin_sp, y = emmean, color = Origin_sp), show.legend = F) +
  geom_errorbar(data = adjusted_min, 
                aes(x = Origin_sp, ymin = asymp.LCL, ymax = asymp.UCL, color = Origin_sp), 
                width = 0.5, linewidth = 1, show.legend = F) +
  geom_point(data = adjusted_min, 
             aes(x = Origin_sp, y = emmean, color = Origin_sp), size = 2, show.legend = F) +
  labs(caption = "Model-adjusted estimates for temperature minimums compared across recording origins",
       y = "Model-Adjusted Temperature", 
       x = "Recording Origin") +
  theme_bw() +
  theme(
    panel.grid = element_blank(), 
    axis.line = element_line(color = "black"),
    axis.title = element_text(size = 18),
    axis.text = element_text(size = 12),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 16),
    plot.caption = element_text(size = 13))


ggplot()+
  geom_jitter(data=Temp_all, alpha=.25, show.legend = F, aes(x=Origin_sp, y=Temp_max, color=Origin_sp)) +
  geom_line(data = adjusted_max, 
            aes(x = Origin_sp, y = emmean, color = Origin_sp), show.legend = F) +
  geom_errorbar(data = adjusted_max, 
                aes(x = Origin_sp, ymin = asymp.LCL, ymax = asymp.UCL, color = Origin_sp), 
                width = 0.5, linewidth = 1, show.legend = F) +
  geom_point(data = adjusted_max, 
             aes(x = Origin_sp, y = emmean, color = Origin_sp), size = 2, show.legend = F) +
  labs(caption = "Model-adjusted estimates for temperature maximums compared across data origins",
       y = "Model-Adjusted Temperature", 
       x = "Recording Origin") +
  ylim(21.5, 31) +
  theme_bw() +
  theme(
    panel.grid = element_blank(), 
    axis.line = element_line(color = "black"),
    axis.title = element_text(size = 18),
    axis.text = element_text(size = 12),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 16),
    plot.caption = element_text(size = 12)) +
  annotate("text", x = 1, y = 31, label = "A", size = 5) +
  annotate("text", x = 2, y = 29.5, label = "A", size = 5) +
  annotate("text", x = 3, y = 26, label = "B", size = 5)

```

